version: '3'

services:
    mongo:
        container_name: mongodjango
        image: mongo
        restart: always
        ports:
            - 27018:27017
    web:
        build: .
        command: python /code/Travel_agency/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        links:
            - mongo