# Generated by Django 3.0.5 on 2021-05-04 05:51

import Currency_formats.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('country_price', models.FloatField()),
                ('currency', djongo.models.fields.EmbeddedField(model_container=Currency_formats.models.Currency_)),
            ],
        ),
    ]
